
repos:

# config from https://black.readthedocs.io/en/stable/integrations/source_version_control.html
#- repo: https://github.com/psf/black
#    rev: 23.7.0
#    hooks:
#      - id: black
#        language_version: python3.10

# config from https://github.com/astral-sh/ruff-pre-commit
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.285
  hooks:
    - id: ruff

